# Generated by Django 5.2.1 on 2025-05-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EBooksModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("summary", models.TextField(max_length=2000)),
                ("pages", models.CharField(max_length=80)),
                ("pdf", models.FileField(upload_to="pdfs/")),
                ("author", models.CharField(max_length=80)),
                ("category", models.CharField(max_length=80)),
                ("author_id", models.IntegerField(default=0)),
            ],
        ),
    ]
